export const VECTORMAIL_SIGNATURE_HTML =
  "<br><br>--<br>Generated by VectorMail";
export const VECTORMAIL_SIGNATURE_PLAIN = "\n\n--\nGenerated by VectorMail";

export function appendVectorMailSignature(
  body: string,
  isHtml = true,
): string {
  const sig = isHtml ? VECTORMAIL_SIGNATURE_HTML : VECTORMAIL_SIGNATURE_PLAIN;
  if (!body?.trim()) return sig.trim();
  return body.trimEnd() + sig;
}
